### PR TITLE
Change Attach values to allow negative numbers

### PR DESCRIPTION
**Pull request by rbran**

### CODE REVIEW

**Comment by mchesser** [comment]
Yeah this makes sense, but I think it will report an error for `u64::MAX` (which I think should be allowed), and I think we do want to report an error when negating `i64::MIN`. Maybe something like this would work?

```rust
let value: u64 = ...;
if !negative {
    // Ignore overflows in cast when 
    return Ok(value as i64);
}
let value = i64::try_from(value)
    .map_err(|e| token.error(format!("invalid number: {e}")))?;
if negative && value == i64::MIN {
    return token.error("attempted to negate i64::MIN which would overflow.");
}
Ok(Some(if negative { -value } else { value }))
```

**Comment by rbran** [comment]
> I think it will report an error for u64::MAX (which I think should be allowed)

This code will also report `invalid number`, because of the `i64::try_from(value)`.

if you want the range to go from `-(u64::MAX)..u64::MAX` the most practical solution will the `i128`. Because  `attach values` define how the value is printed, we need to differentiate a `-1` from `0xffffffff_ffffffff`, what we can't do with `u64` or `i64`.

> `value == i64::MIN`

This will never be true, because at this point `value` is always positive and `i64::MIN` always negative.

**Comment by mchesser** [comment]
The reason I've been holding off on merging this (or the variant using i128) is because I wanted to check the behavior of Ghidra's SLEIGH compiler.

As far as I can tell Ghidra's SLEIGH compiler treats u64::MAX (0xfffffffffffffffff) the same as -1  (I verified this by running `ghidra/support/sleigh -u -t coldfile.slaspec` with the -1 changed to 0xfffffffffffffffff). And does not allow larger values (I get this error when I tried: `ERROR 68000.sinc:323: Integer representation exceeds Java long (0xffffffffffffffffff) (SleighCompile)`).

So to match Ghidra, I believe the correct range is i64::MIN..i64::MAX, with values greater than i64::MAX handled as reinterpreting the result as a negative number.

**Comment by rbran** [comment]
Here my results with `attach values d911 [ -1 1 2 9223372036854775807 9223372036854775808 -9223372036854775808 -9223372036854775809 7 ];`

```
        // d911 = 9223372036854775807 = i64::MAX
        00000000 a7 40           mov3q      #0xffffffff,D0
                                                      D0 = COPY 0xffffffff:4
        // d911 = 9223372036854775808 = i64::MAX + 1
        00000002 a9 40           mov3q      #0x0,D0
                                                      D0 = COPY 0:4
        // d911 = -9223372036854775808 = i64::MIN
        00000004 ab 40           mov3q      #0x0,D0
                                                      D0 = COPY 0:4
        // d911 = -9223372036854775809 = i64::MIN - 1
        00000006 ad 40           mov3q      #0xffffffff,D0
                                                      D0 = COPY 0xffffffff:4
        // d911 = 7
        00000008 af 40           mov3q      #0x7,D0
                                                      D0 = COPY 7:4
```

NOTE: the value is actually reduced to 32bits, that happen because the semantic portion of the constructor affects how the disassemble variable is printed. In this case the `eal = d911` forces the d911 to be printed as a 32bits value, because `eal` is 32bits, I'm not sure why it's printed as unsigned tho.

It seems, that any number that can be read as a java long (u64) is allowed, then it is simply cast to the signed version (`as i64`) allowing overflow.

**Comment by rbran** [comment]
Although this imitate Ghidra, and I understand why you want that, I don't think it was the ghidra programmers intention to allow values to overflow.

Even if this don't create any bugs now, it could allow an unintended behavior by the sleigh programmer on icicle or ghidra itself.

Anyway, this is a problem for the people of the future.

**Pull request merged**
