### PR TITLE
Add Dockerfile.

### PR DESCRIPTION
**Pull request by Tim-Nosco**
This is a simple Dockerfile to build icicle-emu.

Test by running:

`docker build -t icicle-emu .`

Then

```sh
docker run -it --rm \
 -v <YOUR SYSROOT>:/target \
 -e ICICLE_SYSROOT=/target \
 -e ICICLE_ARCH=<YOUR ARCH>\
 icicle-emu \
 ./target/release/afl-icicle-trace \
 <YOUR TARGET>
 ```

Contributed by Research Innovations Inc.

### CODE REVIEW

**Comment by rbran** [comment]
Icicle uses the environment variable `GHIDRA_SRC` to access the sleigh files, you may want to include that to the docker file.

https://github.com/icicle-emu/icicle-emu/blob/master/icicle-vm/src/builder.rs#L475

**Comment by mchesser** [comment]
Thanks for the PR.

Did you have a particular use-case in mind for using Icicle in Docker? My expectation, is that in its current state, it is more usable as a library. 

Additionally, at the moment, I maintain some SLEIGH patches for issues I encountered running certain binaries (mostly x86-64 and MSP430): https://github.com/icicle-emu/ghidra -- which still need to be up-streamed (though it has been a while since I last rebased the patches, so some could be fixed) -- so it might make sense to use that repo instead (I know most MSP430X binaries will fail to run without the patches).

**Comment by Tim-Nosco** [comment]
My primary use-case is for offline development. I install the toolchain and dependencies in docker then move the image over.
I can update the Ghidra source!

**Comment by mchesser** [comment]
Thanks for the context. I'm happy to merge it with the Ghidra source updated. Long term, it would be good to upstream the patches and go back to the base Ghidra repo, but for now using the patched repo what I recommend since it is the most well tested option.

**Pull request merged**
